const QUERY_KEYS = {
  AUTHENTICATE: "AUTHENTICATE",
  FAVOURITE_ITEMS: "FAVOURITE_ITEMS",
  RELATIVE_EPISODES: "RELATIVE_EPISODES",
  GENRES: "GENRES",
  PODCASTS: "PODCASTS",
  HOME_FEEDS: "HOME_FEEDS",
};

export { QUERY_KEYS };
